import { useRouter } from "next/router";
import Image from "next/image";
import Head from "next/head";

const News = (data: any) => {
  const router = useRouter();
  const { id } = router.query;
  const news = data.data.data[`${id}`];

  if (news) {
    return (
      <>
        <Head>
          <title>Artikel {parseInt(news.id) + 1}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://www.idntimes.com/favicon.png" />
        </Head>
        <article className="md:mt-0 my-4">
          <h2 className="text-xl font-bold my-2">{news.title}</h2>
          <Image
            src={news.img}
            alt="Picture of the author"
            className=" h-auto  my-4"
            width={640}
            height={480}
            priority={true}
          />
          <p className="text-idn-grey">
            {news.category.charAt(0).toUpperCase() + news.category.slice(1)} -
            Courtesy: @{news.author}
          </p>
          <p className="my-4">
            <span className="font-bold">Jakarta, IDN Times </span> -{" "}
            {news.paragraph}
          </p>
          <p>{news.paragraph}</p>
        </article>
      </>
    );
  } else {
    return <div>no such news</div>;
  }
};

export async function getServerSideProps(context) {
  const { params } = context;

  const { id } = params;
  const response = await fetch(`http://localhost:3000/api/news?id=${id}`);

  const data = await response.json();
  return {
    props: {
      data,
    },
  };
}

export default News;
