import "../styles/global.css";
import Head from "next/head";

import type { AppProps } from "next/app";

import { useEffect, useState } from "react";
import ProfileComponent from "../components/home/Profile";

function MyApp({ Component, pageProps }: AppProps) {
  const [profileData, setProfileData] = useState({
    img: "",
    full_name: "",
    bio: "",
    following: 0,
    followers: 0,
  });

  useEffect(() => {
    fetchProfile();

    window.scrollTo(0, 0);
  }, []);

  const fetchProfile = async () => {
    try {
      const response = await fetch("/api/profile");
      const data = await response.json();

      setProfileData(data);
    } catch (error) {
      throw error;
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.idntimes.com/favicon.png" />
      </Head>
      <div className="m-5">
        <ProfileComponent profileData={profileData} />
        <div
          className="border-b-1 mt-4 border border-[#e2e8f0]"
          style={{
            width: "100vw",
            position: "relative",
            left: "calc(-50vw + 50%)",
          }}
        ></div>
        <Component {...pageProps} profileData={profileData} />
      </div>
    </>
  );
}

export default MyApp;
